SENDER_EMAIL = ""  # Ваш email
SENDER_PASSWORD = ""   # Ваш пароль или пароль приложения
SMTP_SERVER = ""
SMTP_PORT = 465
DB_NAME = ""
AUTH_KEY = ""
IMG_KEY = ""
PAYPAL_CLIENT_ID = ""
PAYPAL_CLIENT_SECRET = ""
PAYPAL_API_URL = ""
SECRET_KEY = ""
